# Generated by Django 5.2 on 2025-05-02 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeightTrackerElements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date of measurement",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in Kilograms", max_digits=5
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Weight Entries",
                "ordering": ["-date"],
            },
        ),
    ]
